### ISSUE TITLE
Possible wrong use of the "@SideOnly(Side.CLIENT)" 

### ISSUE THREAD

**Issue by broncotc** [CovertJaguar/Railcraft-API#35] opened 2019-02-12 05:50 UTC
The current file [Charge.java](https://github.com/Railcraft/Railcraft-API/blob/b6e0040176c304d788cb9ef780fee4a89bcc91b9/src/main/java/mods/railcraft/api/charge/Charge.java) consists 2 decorators of "@SideOnly(Side.CLIENT)" which will cause the mod built from trunk to crash. I was testing truck build due to the sponge incompatibility of the current beta 4 release.  
In construction stage of loading module "charge", it throws an exception: "java.lang.RuntimeException: Attempted to load class mods/railcraft/api/charge/Charge$IZapEffectRenderer for invalid side SERVER". This implies the behavior of the decorator "@SideOnly(Side.CLIENT)" might be resisting the entire class/enum from loading instead of strip certain methods from a loadable class on the server side. 
What I described here is **not** matching with the behavior documented here: [ForgeDoc/Concepts/Sides](https://github.com/MinecraftForge/Documentation/blob/master/docs/concepts/sides.md) , but removing the 2 "sideonly" decorations will make it load and work in the sponge server. Also the forge doc do suggest to not use this decoration except certain very specific circumstances. 

Version numbers for your reference:
Forge: 14.23.5.2811
SpongeForge: 1.12.2-2768-7.1.5
Buildcraft: current git
Java: openjdk version "1.8.0_171"

Thank you for investigating into this.

**Comment by CovertJaguar** [comment] 2019-02-12 20:04
I admit something did feel off about #33. Hopefully it doesn't cause any issues with running on a normal dedicated server.

**Comment by liach** [comment] 2019-02-12 20:07
Duplicate of #33

**Comment by liach** [comment] 2019-02-12 20:08
The cause is clear: The code referencing the field is not removed in `<clinit>`. The modified version of #33 has fixed it.

**Closed as completed by liach** 2019-02-12 20:08 UTC
Labels: duplicate, bug, high priority
